backend:
  name: git-gateway
  branch: master

media_library:
  name: cloudinary
  config:
    cloud_name: artists
    api_key: 118677734871395
media_folder: /static/img
public_folder: /img

collections:
  - name: "artist"
    label: "Artist"
    folder: "models/artist"
    extension: "json"
    create: true
    slug: "index"
    path: "{{name}}/data"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Spotify", name: "spotify", widget: "string" }
      - { label: "Instagram", name: "instagram", widget: "string" }
      - { label: "Souncloud", name: "soundcloud", widget: "string" }
      - { label: "Bandcamp", name: "bandcamp", widget: "string" }
      - {
          label: "Curated Playlist",
          name: "curated_playlist",
          widget: "string",
        }
      - {
          label: "Soundcloud Release TrackId",
          name: "soundcloud_release_trackId",
          widget: "string",
        }
