backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "artist"
    label: "Artist"
    folder: "models/artist"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{name}}/index"
    editor:
      preview: false
    fields:
      - { label: "Spotify", name: "spotify", widget: "string" }
      - { label: "Instagram", name: "instagram", widget: "string" }
      - { label: "Souncloud", name: "soundcloud", widget: "string" }
      - { label: "Bandcamp", name: "bandcamp", widget: "string" }
